Revert "Update to NixOS 19.09"
It fails in stage 2 on nix-env -i pcre:

	starting /nixos-in-place/stage2...
	error: selector 'pcre' matches no derivations

This reverts commit 5831401ff0a40607a80d774d29a41a271660401a.