Update to NixOS 19.09
Doesn't work yet. It fails in stage 2 on nix-env -i pcre:

	starting /nixos-in-place/stage2...
	error: selector 'pcre' matches no derivations